name        = "GACM"
version     = "0.1.0"
description = "A short summary on this project"
license     = "Public Domain"
author      = "ahmathlete"
maintainer  = "Ahmathlete"
copyright   = "Copyright 2023, ahmathlete"
categories  = ["Climate Modelling"]
[build]
auto-executables = true
auto-tests       = true
auto-examples    = true
external-modules = "netcdf"
[install]
library = true
[library]
source-dir="src"

