name = "GACM"
version = "0.1.0"
license = "license"
author = "ahmathlete"
maintainer = "Ahmed.a.b.Homoudi@gmx.de"
copyright = "Copyright 2023, ahmathlete"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
